version: '3'
services:
  traefik:
      image: traefik
      command: -c /dev/null --web --docker
      labels:
        - "traefik.enable=false"
      ports:
        - "80:80"
        - "8080:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  recruitment:
    image: soa/recruitment
    labels:
      - traefik.port=8080
      - traefik.backend=app
      - traefik.frontend.rule=PathPrefixStrip:/app
    depends_on:
      - traefik
      - db
    links:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soa-recruitment-db